// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./Home.bs.js";
import * as React from "react";
import * as PageNotFound from "./PageNotFound.bs.js";
import * as RescriptReactRouter from "../node_modules/@rescript/react/lib/es6_global/src/RescriptReactRouter.bs.js";

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (match) {
    return React.createElement(PageNotFound.make, {});
  } else {
    return React.createElement(Home.make, {});
  }
}

var make = App;

export {
  make ,
  
}
/* Home Not a pure module */
