// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function PageNotFound(Props) {
  return React.createElement("div", {
              className: "bg-white min-h-full px-4 py-16 sm:px-6 sm:py-24 md:grid md:place-items-center lg:px-8"
            }, React.createElement("div", {
                  className: "max-w-max mx-auto"
                }, React.createElement("main", {
                      className: "sm:flex"
                    }, React.createElement("p", {
                          className: "text-4xl font-extrabold text-indigo-600 sm:text-5xl"
                        }, "404"), React.createElement("div", {
                          className: "sm:ml-6"
                        }, React.createElement("div", {
                              className: "sm:border-l sm:border-gray-200 sm:pl-6"
                            }, React.createElement("h1", {
                                  className: "text-4xl font-extrabold text-gray-900 tracking-tight sm:text-5xl"
                                }, "Page not found"), React.createElement("p", {
                                  className: "mt-1 text-base text-gray-500"
                                }, "Please check the URL in the address bar and try again")), React.createElement("div", {
                              className: "mt-10 flex space-x-3 sm:border-l sm:border-transparent sm:pl-6"
                            }, React.createElement("a", {
                                  className: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500",
                                  href: "#"
                                }, "Go back home"), React.createElement("a", {
                                  className: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500",
                                  href: "#"
                                }, "Contact support"))))));
}

var make = PageNotFound;

export {
  make ,
  
}
/* react Not a pure module */
