// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as SubscriberGen from "./Subscriber.gen";

function connect(prim) {
  return SubscriberGen.connect(prim);
}

function start(param) {
  var cli = SubscriberGen.connect("abc");
  var err = Curry._1(cli.subscribe, Curry._1(cli.on, "connect"));
  if (!err) {
    Curry._1(cli.publish, [
          "presence",
          "hello mqtt"
        ]);
  }
  Curry._1(cli.on, "message");
  console.log("test");
  console.log(undefined);
  return cli.end;
}

export {
  connect ,
  start ,
  
}
/* ./Subscriber.gen Not a pure module */
